### ISSUE TITLE
Sometimes airdrops spawn with just 1 item replacing all the other ones

### ISSUE THREAD

**Issue by Daniil1288** [RestoreMonarchyPlugins/AirdropManager#1]
Examples:
![image](https://user-images.githubusercontent.com/1404955/61631197-61f29000-ac92-11e9-8c23-12c57bd36274.png)
![image](https://user-images.githubusercontent.com/1404955/61631200-64ed8080-ac92-11e9-8948-3595e9e674b7.png)
![image](https://user-images.githubusercontent.com/1404955/61631209-69199e00-ac92-11e9-96f5-5839c7bee7fb.png)

**Comment by RestoreMonarchy** [comment]
Hello @Daniil1288 

I just pushed a simplified and more clean version of the plugin. It should do the same however works a bit else. 
I just uploaded the build to the Rocket Harbor, Build #26. Could you test it and tell me if it works and the issue is fixed?

Regards,
MCrow

**Comment by Daniil1288** [comment]
@RestoreMonarchy 
Now doing /airdrop results in a default airdrop.
![image](https://user-images.githubusercontent.com/1404955/61728113-40ba9e00-ad7d-11e9-90af-0fabd69573ea.png)
Cfg file: https://pastebin.com/raw/hV763KEC

**Comment by Daniil1288** [comment]
![image](https://user-images.githubusercontent.com/1404955/61728950-e3bfe780-ad7e-11e9-992c-7bcd43e120c8.png)
Without doing /airdrop (on timer)

**Comment by RestoreMonarchy** [comment]
Hello again @Daniil1288 

I'm glad to say that the issue should be fixed now and all should be working as it's supposed to. I did some tests on my local computers and the default configuration seems to be working fine to me.
Within 5' minutes from now the new version Build #27 should be available on Rocket Harbor, please if you can, let me know if it also works for you, so if it's all fine I'll can close this issue.

Thank you for your time @Daniil1288 
Regards,
MCrow

**Comment by Daniil1288** [comment]
Well, using the same config results in all summoned airdrops using /airdrop to fall in one place in the water: 
![image](https://user-images.githubusercontent.com/1404955/61869864-58149b00-aee5-11e9-8860-1283fcf71b13.png)
Modded items do spawn, though. Thank you for fixing that.
Also, tried spamming /airdrop around 20 times but only 3 airplanes spawned, although the airdrop messages do pop up in chat. Is this expected behaviour?

**Comment by Daniil1288** [comment]
@RestoreMonarchy

**Comment by RestoreMonarchy** [comment]
Hey @Daniil1288 

I fixed these both issues, so everything should be working now. Give Build #28 a try and tell me if you find any more bugs.

Thank you for your help,
MCrow

**Comment by Charterino** [comment]
i found a bug mcrow supports lgbt

**Comment by Daniil1288** [comment]
Thank you very much, all works as intended!

**Comment by Daniil1288** [comment]
Whoops, the bug is back, apparently.
![image](https://user-images.githubusercontent.com/1404955/62821341-e3e02580-bb7b-11e9-95fb-1afa94fc6046.png)
[Config](https://pastebin.com/raw/A2heDDhy)

**Comment by RestoreMonarchy** [comment]
Yeah it got back after the latest Unturned update. I'll have a look at it today, but will probably completely change the way it works to make it more stable for future.

**Comment by Daniil1288** [comment]
@RestoreMonarchy, any updates?

**Comment by RestoreMonarchy** [comment]
@Daniil1288 Yes the plugin works however it has changed a lot and works different way now. Now you choose what items exactly should be in the airdrop

**Comment by RestoreMonarchy** [comment]
Hey @Daniil1288 I've recently fixed the plugin and now it has all the features back from past and the bug is fixed. I also made some improvements and code cleaning. 
It's available on Rocket Harbor: https://harbor.rocketmod.net/plugins/airdropmanager/

Please keep reporting me any future bugs,
Thank You for contribution and sorry for that late update

**Comment by Daniil1288** [comment]
@RestoreMonarchy, Hey,
Yeah, the plugin works as expected now, thank you very much!
So far I've had some trouble getting the MoreHomes new update (not sure if it was meant to be tested out) working and I've reported it in that plugin's issue section.
Also had some minor quirks with your Teleportation plugin: the plugin tells the player that he has to wait, for example, 75,5721748 seconds before requesting TPA again instead of just saying '75 seconds' like the other plugins. [Screenshot here](https://media.discordapp.net/attachments/638393817455919125/638437812470939698/20191028220350_1.jpg) if you don't mind me not creating another issue for it.

**Comment by RestoreMonarchy** [comment]
Hey,

Thanks for the report about Teleportation plugin, I'll be releasing update for Teleportation plugin (to support MoreHomes) and complete rewrite of MoreHomes to work much better now. You'll find out more later today I have to write a new MoreHomes plugin description and surely gonna fix the Teleportation to round the number.
